name: fordfisher
favicon: null
layout_spectrum: 0.22287
typography_spectrum: 0.64769
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7549232500605285
  lightness: 0.18331316974945366
  saturation: 0.17580303899012506
  rhythmicContrast: 0.6614947328343987
purpose: []
